### ISSUE TITLE
JAM logo animation segfaults

### ISSUE THREAD

**Issue by jonathangray** [bibendovsky/bstone#114]
The JAM logo animation causes bstone to segfault on OpenBSD/amd64.

bstone built from  4fa973038735244f26dc279d2c4bae57aae71fc9 (1.1.10) with clang 6.0.0

Occurs with Aliens of Gold shareware and full versions of Aliens of Gold and Planet Strike from the Apogee Throwback Pack.

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__is_long (this=0x0)
    at /usr/include/c++/v1/string:1255
1255            {return bool(__r_.first().__s.__size_ & __short_mask);}
[Current thread is 1 (process 185605)]
(gdb) bt
#0  std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__is_long (this=0x0)
    at /usr/include/c++/v1/string:1255
#1  std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::size (this=0x0)
    at /usr/include/c++/v1/string:896
#2  std::__1::operator+<char, std::__1::char_traits<char>, std::__1::allocator<char> > (__lhs=..., __rhs=...)
    at /usr/include/c++/v1/string:3769
#3  0x00000ad8d0dd3ab7 in ca_open_resource_non_fatal (data_dir=..., file_name_without_ext=..., file_extension=..., file_stream=...)
    at /usr/users/jsg/src/bstone/src/id_ca.cpp:1147
#4  0x00000ad8d0dd3d9f in ca_open_resource_non_fatal (file_name_without_ext=..., file_extension=..., file_stream=...)
    at /usr/users/jsg/src/bstone/src/id_ca.cpp:1181
#5  0x00000ad8d0dd175a in ca_open_resource (file_name_without_ext=..., file_stream=...)
    at /usr/users/jsg/src/bstone/src/id_ca.cpp:1193
#6  0x00000ad8d0e2c3ad in MOVIE_Play (MovieStuff=0xadb57515680) at /usr/users/jsg/src/bstone/src/movie.cpp:528
#7  0x00000ad8d0d46a1d in DoMovie (movie=mv_intro, palette=0x0) at /usr/users/jsg/src/bstone/src/3d_main.cpp:9463
#8  0x00000ad8d0e09361 in PreDemo () at /usr/users/jsg/src/bstone/src/jm_free.cpp:986
#9  0x00000ad8d0e09fd1 in freed_main () at /usr/users/jsg/src/bstone/src/jm_free.cpp:1165
#10 0x00000ad8d0d4864f in main (argc=1, argv=0x7f7ffffc63a8) at /usr/users/jsg/src/bstone/src/3d_main.cpp:9805
```
In the proposed OpenBSD port @ibara commented out the call to DoMovie() due to this segfault.

**Comment by bibendovsky** [comment]
Please check with #117. Should fix the segfault.

**Comment by jonathangray** [comment]
Thanks, I built the develop branch (4de08378cd7ad73ee69bd1c07b08d737814261ad)  which includes the 'Use method instead field to avoid initialization order fiasco' change and indeed the segfault is fixed.
